### ISSUE TITLE
[Enhancement]: The feedback of Doc "Install standalone MatrixOne" 

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixorigin.io#115]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

1. In general, documents begin with an overview of the content and objectives of the document, so that others can quickly know what the document can work through. U can refer to the docs of CRDB of TiDB.

2. General hardware and software requirements are mainly emphasized, and a sub-chapter is opened. It doesn't seem obvious right now.
<img width="728" alt="image" src="https://user-images.githubusercontent.com/87641339/201038827-ccc676c5-8a69-4704-b36d-5f2504b130a5.png">

3. We offered three methods to install MO,  whether each is targeted at different operating systems or developers, or matches to development dev habits, and which one is recommended for different developers, etc.

4. install go as necessary independency, can you give a basic description, where to go to download, and how to next step, give a personal experience as u pass the main path, ensure that along the suggested path, the go software can install successfully.

5. install mysqlclient. Is it required in the install section or connect to mo server? It is written in both documents, and in install doc, it writes only the suggested version, the version can be clicked to jump to a Windows-only download page, and for mac computers, the path is broken. Still, can you give a basic description, where to go to download, and how to next step, give a personal experience as u pass the main path, ensure that along the suggested path, the mysql client can install successfully.

6. 
<img width="706" alt="image" src="https://user-images.githubusercontent.com/87641339/201039939-92248500-0d6c-4dac-941b-79b23303ab8a.png">
 == The command suggested above is not the same as the command copied below. We have the same problem in option2.

7. 
<img width="691" alt="image" src="https://user-images.githubusercontent.com/87641339/201040078-f57eac10-152d-4a86-b1fa-1ddf0251ef92.png">
 ==3 methods, what is the target for each of them? What method should we use when encountering what problem?

8. 
<img width="495" alt="image" src="https://user-images.githubusercontent.com/87641339/201040219-771083d1-0219-404b-9d87-136a48c6fb74.png">
== There is no space between the number and letter here.

9.
<img width="720" alt="image" src="https://user-images.githubusercontent.com/87641339/201040293-1d93ad9e-09f6-4ef2-a8fc-871a69328280.png">
 == Then what? After using this command to verify, how do I install docker if it is not installed ? What should I do if it reports an error?

**Comment by lacrimosaprinz** [comment]
I rewrite these sections:https://github.com/matrixorigin/matrixorigin.io/pull/118
