### ISSUE TITLE
[Enhancement]: Grant needs more details

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#116]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.io/dev/MatrixOne/Reference/SQL-Reference/0.6-Database-Administration-Statements/grant-privileges/
https://docs.matrixorigin.io/dev/MatrixOne/Reference/SQL-Reference/0.6-Database-Administration-Statements/grant-role/

We need more details about the grant and privilege, what kind of privileges are possible?  Who has right to grant to whom?
For users, where do they find what kind of privilege they have?  In what case they need to interact with the grant and privilege ?

**Comment by lacrimosaprinz** [comment]
edit the docs here：https://github.com/matrixorigin/matrixorigin.io/pull/123
