### ISSUE TITLE
[Enhancement]:  Built-in functions inside INSERT INTO...VALUES(function) syntax is supported now.

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#124]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

Please remove this constraint and add a new example: @lacrimosaprinz 
https://docs.matrixorigin.io/dev/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/0.6-insert/

**Comment by lacrimosaprinz** [comment]
remove constraint and add example：insert into t1 values(DATE("2017-06-15 09:34:21")),(DATE("2019-06-25 10:12:21")),(DATE("2019-06-25 18:20:49"));https://docs.matrixorigin.io/dev/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/insert/#examples
