### ISSUE TITLE
[Enhancement]:  MySQL Compatibility needs to be updated

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#133]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

It looks like this mysql compatibility is still as 0.5.1. 

A lot of new features have not been updated.

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/167
