### ISSUE TITLE
[Enhancement]: Remove upgrade chapter

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#134]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.io/dev/MatrixOne/Maintain/upgrade-standalone-matrixone

0.6 doesn't have in-version upgrade yet, remove this chapter.

**Comment by lacrimosaprinz** [comment]
removed: https://github.com/matrixorigin/matrixorigin.io/pull/137
