### ISSUE TITLE
[Enhancement]:  unnest function description needs to be improved

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#135]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

1. Typo error. 
<img width="257" alt="image" src="https://user-images.githubusercontent.com/4965857/203918153-ccbff551-a1ae-429c-b1f2-5f2d2606f83b.png">
2. The category for unnest function should be JSON. 
3. MatrixOne doesn't support ARRAY yet. so the description is not exact at all.
<img width="736" alt="image" src="https://user-images.githubusercontent.com/4965857/203918415-d3468495-7105-4f99-8897-113ff0a63867.png">

**Comment by lacrimosaprinz** [comment]
@lacrimosaprinz    catalog --> json
                         rewrite unnest topic
