### ISSUE TITLE
[Displaying]: stream engine

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#146]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

https://docs.matrixorigin.io/dev/MatrixOne/Overview/matrixOne-architecture-design/#streeam-engine

1. typo issue
<img width="723" alt="image" src="https://user-images.githubusercontent.com/4965857/204219472-9610a9f2-3104-4557-bc53-a9ffb95d4086.png">

2. 
Instead of `Coming soon`, please also add this description about this Stream Engine:

```
The streaming engine is a new component to ease users' streaming join ETL process from OLTP to OLAP. It is planned in the MatrixOne roadmap but not implemented yet. 

```

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/157
