### ISSUE TITLE
[Enhancement]: update get started to 0.6 version

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#147]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.io/dev/MatrixOne/Get-Started/install-standalone-matrixone

1. update binary package and checkout branch to 0.6.
2. launch mo-server with with new quickstart config.
3. update docker install version.
4. remove the upgrade version link.
5. Add a reference to the full distributed installation.
<img width="658" alt="image" src="https://user-images.githubusercontent.com/4965857/204225768-55fd3d48-5106-4830-a073-a0cd476010bb.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/152
