### ISSUE TITLE
[Displaying]:  the table of content is on the right

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#148]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

https://docs.matrixorigin.io/dev/MatrixOne/Develop/connect-mo/client-connect-to-matrixone/

Why on this page, the table of content is on the right?

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/4965857/204225475-7178f60e-02e1-4836-afd5-e3d9c0e5b784.png">

**Comment by lacrimosaprinz** [comment]
Tihis is the right link https://docs.matrixorigin.io/dev/MatrixOne/Develop/connect-mo/database-ide/#connect-to-the-matrixone-server-through-dbeaver
