### ISSUE TITLE
[Enhancement]: Transaction chapter needs to be reformated

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#150]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

The distributed transaction page has a lot of transaction concept explaining, which should be in the transaction overview page.  
We may reformat this chapter as 

-Transaction Basics
-MatrixOne transaction design
     * Standalone transaction
     * Distributed transaction
-How to use MatrixOne transaction

**Comment by lacrimosaprinz** [comment]
https://docs.matrixorigin.io/dev/MatrixOne/Develop/connect-mo/database-ide/#connect-to-the-matrixone-server-through-dbeaver
