### ISSUE TITLE
[Enhancement]: one mistake in Launch MatrixOne server doc

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixorigin.io#161]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

<img width="723" alt="image" src="https://user-images.githubusercontent.com/87641339/204988727-f3d2a96e-f0f2-4744-8c3c-0d3d90ae32d5.png">
 the description in the doc and code block is not the same

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/168
