### ISSUE TITLE
[Enhancement]: Some questions in Basic SQL Doc

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixorigin.io#162]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

<img width="995" alt="image" src="https://user-images.githubusercontent.com/87641339/204992566-8f5282c9-6a8c-4278-95ae-6ce655438710.png">

is it DCL or DAL? it does not look the same. And what does it mean? should we add a full name of the abbreviation?

**Another mistake: role not rule.**
<img width="732" alt="image" src="https://user-images.githubusercontent.com/87641339/204993231-51f3299c-539a-4fe6-a14c-7fbbc4a430c2.png">
and I am not sure, what does the role_r1,role_r2,role_r3 mean? is it meaningful? and where can I find the description of these  three roles? add a link about this?

**Another question about grant:**
why check the privileges of root? I did operations of mouser all the time, and nothing about root. and after I did the operations of mouser about grants, the result is still empty. is there some problem here?
<img width="546" alt="image" src="https://user-images.githubusercontent.com/87641339/204994479-65c031f6-6c9f-49af-8127-ebb6f55edeec.png">

<img width="418" alt="image" src="https://user-images.githubusercontent.com/87641339/204994883-391065bf-84b7-4c35-ab2a-bcf430ef190b.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/233
