### ISSUE TITLE
[Enhancement]: some suggestions in create table doc

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixorigin.io#163]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

1. the create table statement put in as the explanation, weird.
<img width="980" alt="image" src="https://user-images.githubusercontent.com/87641339/205021840-54fd497c-2c80-4a14-b946-26a7b92b17b4.png">

2. the temporary table link name is different with the chapter name.
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/87641339/205022572-7c877e46-9a6c-477c-a0f7-bfc74e12adef.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/168
