### ISSUE TITLE
[Enhancement]: Database Client IDE

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#164]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

1. title is not correct. Only Navicat and DBeaver are IDE tools, MySQL client is not an IDE. 
<img width="237" alt="image" src="https://user-images.githubusercontent.com/4965857/205196470-378aa21c-bc51-471f-af76-750c1ff51cf6.png">

2. "MySQL shell" --> "MySQL Client".
<img width="689" alt="image" src="https://user-images.githubusercontent.com/4965857/205196530-25ce33f7-0bdf-4cc0-b4f7-4b0158960c9f.png">

3. By default setting, navicat connection will experience some bugs for now, we need specify it.

4. Add HeidiSQL support for windows.

5. Put some connection screenshots for these tools.

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/170    rename the topic name
https://github.com/matrixorigin/matrixorigin.io/pull/172     rename the navigation name
