### ISSUE TITLE
[Displaying]: MatrixOne directory structure

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#166]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

it looks like the displaying is not correct.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/4965857/205198125-67126b4c-0dd0-4e70-898a-ca4459fe8829.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/168
