### ISSUE TITLE
[Enhancement]: data type overview

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#173]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

Many errors:

1. For string types:
-char and varchar doesn't have a 24 bytes fixed length. 
-text has variable length up to 2^30-1(which is 1073741823 bytes at most).
-We need to specify other text syntax, such as tiny text, medium text, etc. 
<img width="507" alt="image" src="https://user-images.githubusercontent.com/4965857/206395188-0e7e331f-bd30-45cc-bb57-394ca079e1b5.png">

2. For blob types, we only have one implementation as BLOB type. all other types are a syntax mapping to the BLOB type.
The BLOB type is equal to TEXT type, variable length up to 2^30-1(which is 1073741823 bytes at most).

3. JSON type:
this whole table is clearly wrong.
<img width="711" alt="image" src="https://user-images.githubusercontent.com/4965857/206395946-c1b2b248-1f41-421f-84cf-53c72516e40b.png">

4. Time and Date Types:
-need to confirm with R&D about TIME type size, MySQL only uses 3 bytes. 
-all resolutions need to be updated. 

<img width="719" alt="image" src="https://user-images.githubusercontent.com/4965857/206396722-283ac5bc-7023-4aa4-b525-c236a147eb2e.png">

5. Split examples and put them under each data type category.

**Comment by lacrimosaprinz** [comment]
4. Time and Date Types:
-need to confirm with R&D about TIME type size, MySQL only uses 3 bytes.        --->Confirmed. No modification is required here
-all resolutions need to be updated.       --->updated.  modify the resolutions to  microsecond

**Comment by lacrimosaprinz** [comment]
5. Split examples and put them under each data type category.
    ------->Modified
