### ISSUE TITLE
[Enhancement]: The BLOB and TEXT Types

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#174]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

1. title and navigation don't match
2. a lot of wrong description about BLOB and TEXT.

**Comment by lacrimosaprinz** [comment]
Fixed and Merged: https://github.com/matrixorigin/matrixorigin.io/pull/182
