### ISSUE TITLE
[Enhancement]: JSON type doc

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#175]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

This is a blind copy from MySQL JSON type, but a lot of details are not confirmed. 
Need a refactor. 

reference design doc：https://github.com/matrixorigin/matrixone/tree/main/pkg/container/bytejson

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/257
