### ISSUE TITLE
[Enhancement]: understanding the query plan

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#176]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

The whole chapter has several issues:
1. the title and content don't match. The query plan overview is a big concept to be explained. But we put explain usage there.
2. For Using EXPLAIN to learn the execution plan, we see explain and explain analyze.

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/251
