### ISSUE TITLE
[Enhancement]:  tpcc repo is private

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#177]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.io/0.6.0/MatrixOne/Tutorial/TPCC-test-with-matrixone/

the first step won't pass as 
```
git clone https://github.com/matrixorigin/mo-tpcc.git
```

is a private repo.

**Comment by lacrimosaprinz** [comment]
<img width="561" alt="image" src="https://user-images.githubusercontent.com/43231571/215390348-8fea0832-8308-4afb-855c-42ad83443482.png">
[tpcc](https://github.com/matrixorigin/mo-tpcc.git) is a public repo now.
