### ISSUE TITLE
[Enhancement]: tpcc chapter

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#178]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue
1. this should be mo-tpcc
<img width="703" alt="image" src="https://user-images.githubusercontent.com/4965857/206621509-9bfee7d4-f673-47db-977d-2a9f6d2915ae.png">

2.it looks like a java environment is necessary to run this script.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/4965857/206621705-44f4217e-aa9d-4839-85d4-01adcd4b0024.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/222
