### ISSUE TITLE
[Enhancement]: tpcc load data is too slow

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#179]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

[root@VM-0-8-centos mo-tpcc-main]# ./runLoader.sh props.mo warehouse 10
Starting BenchmarkSQL LoadData

props.mo
driver=com.mysql.cj.jdbc.Driver
conn=jdbc:mysql://127.0.0.1:6001/tpcc?characterSetResults=utf8&continueBatchOnError=false&useServerPrepStmts=true&alwaysSendSetIsolation=false&useLocalSessionState=true&zeroDateTimeBehavior=CONVERT_TO_NULL&failoverReadOnly=false&serverTimezone=Asia/Shanghai&enabledTLSProtocols=TLSv1.2&useSSL=false
user=dump
password=***********
warehouses=1
loadWorkers=4
fileLocation (not defined)
csvNullValue (not defined - using default '')

Worker 000: Loading ITEM
Worker 001: Loading Warehouse      1

this takes too much time, need to change the load data method.

**Comment by lacrimosaprinz** [comment]
@aressu1985   can the load data method be changed to improve？
