### ISSUE TITLE
[Displaying]: broken link

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#180]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/4965857/206639844-450288d6-f84d-451a-bab2-ca7f9142d087.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/190
