### ISSUE TITLE
[Displaying]: the edit button is no longer functional

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#183]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

If we click on any edit button, we cannot edit the page. 

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/4965857/207216626-f1c474eb-ea07-4f4a-b197-6d92b2917b52.png">

**Comment by lacrimosaprinz** [comment]
@xuoutput   Pls fix this theme bug

**Comment by xuoutput** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/193 done
