### ISSUE TITLE
[Doc Request]: Cluster by doc

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#202]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

Cluster by is a new feature for increasing performance used in DDL. 
Need a full doc on that for 0.7.

**Comment by lacrimosaprinz** [comment]
记录：加入ddl

**Comment by lacrimosaprinz** [comment]
add into ddl
