### ISSUE TITLE
[Enhancement]: doc file structure improve

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#210]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

The current doc files inside the tutorial folder serve multiple chapters. 
need to put them to right folders. 

<img width="298" alt="image" src="https://user-images.githubusercontent.com/4965857/208431090-ca5559e3-6dd8-4345-9ea8-76bcca4d1843.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/222
https://github.com/matrixorigin/matrixorigin.io/pull/220
