### ISSUE TITLE
[Enhancement]: Some suggestions in Doc "Deploy standalone MatrixOne"

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixorigin.io#223]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

为了方便描述，这个issue用中文了。此issue为建议，可进一步讨论，不急调整。

目前Deploy standalone MatrixOne 作为quickstart安装文档，合并后，整体的内容翔实程度是很好的，值得肯定。就目前文档的观感、简洁感和减少跳转层面提出一些建议：

1. 这个文档是否拆为2篇，例如：Quickstart on MacOS, Quickstart on Linux。或者Install Standalone MatrixOne on MacOS, Install Standalone MatrixOne on Linux。
2. 每个文档内，按照build method 直接显示切换3个tab。
3. 每个tab内，不用明显分2个step，而是按步骤从头写到尾即可。因为step1其实也写了connect，然后上下再互相引用跳转，不是很有必要。
4. 一些英文描述可以简洁些，例如MacOS后面不用加environment, Get the MatrixOne(Develop Version) code to build 可以直接写Develop Version，把一些标题里已有的和上下文已有的重复英文描述可以省略。
5. 有一些标题可以不一定在右侧小目录显示，避免右侧目录导引看起来也很长，但这个等前几项调整后可以再看，不具备具体代表。

**Comment by lacrimosaprinz** [comment]
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/43231571/215389828-6e081529-c693-40c7-a299-e2e9ca8cabd9.png">
2. 每个文档内，按照build method 直接显示切换3个tab。
=============>
这里tab嵌套不容易实现，我还是拆开成了三个文档，看看这种方式可不可行？ @florashi181

**Comment by florashi181** [comment]
只有这一个地方影响了嵌套么？如果只有这个地方，是我的话，maybe会选择方式用tab切换，依赖的wget/curl选一个主链路的写，然后不常用的放到一个新的更多依赖工具的文档里做链接指引。

**Comment by lacrimosaprinz** [comment]
这里只是一个例子，产生嵌套的地方有：
【通过源码构建】
1. 下载稳定版本（0.6.0分支）还是最新版本（main分支）
2. 前台启动还是后台启动
【通过二进制包构建】
1. 安装wget 或 安装 curl
2. 使用 wget 指令下载二进制包 或 curl 指令下载二进制包
3. 前台启动还是后台启动

因为我们的方式比较多，我还是拆开了，看了MongoDB、mysql 也是拆了的：
- mysql:
<img width="304" alt="image" src="https://user-images.githubusercontent.com/43231571/215941310-bac203cf-40a6-40c7-9554-2a931f51be9b.png">
- mongodb
<img width="292" alt="image" src="https://user-images.githubusercontent.com/43231571/215941422-0bed3b74-aa40-4f5f-a9da-781dd278a38e.png">
- tidb是tab切换但是没有嵌套
<img width="741" alt="image" src="https://user-images.githubusercontent.com/43231571/215942344-69690912-4fca-478a-b364-9ce99d1f8471.png">
- singlestore是拆了linux和k8s
<img width="351" alt="image" src="https://user-images.githubusercontent.com/43231571/215942482-128a4476-abbc-42ce-9cdd-f23c7d068dba.png">

我比较倾向于拆开文档   @dengn @florashi181
