### ISSUE TITLE
[Enhancement]: some suggestions in doc"CREATE DATABASE"

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixorigin.io#243]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

1. Create Database Diagram ===this is usually called "Synopsis". And I think this part is written long ago, and many new statements don't have this or need diagram update . so what is the plan of this part, I'm a little confused. 

3. examples== usually also put the return or result? and show databases to show the expected result? well this statement is very easy, maybe it is not very important, still suggest to have a  plan to keep the consistency.

**Comment by lacrimosaprinz** [comment]
1.Create Database Diagram ===this is usually called "Synopsis". And I think this part is written long ago, and many new statements don't have this or need diagram update . so what is the plan of this part, I'm a little confused.
=========>
I compared MySQL Docs and Tidb Docs. Mysql has no syntax diagram; Tidb is a syntax diagram and a grammar structure, and no one of us maintains the syntax diagram, so I removed them all.
