### ISSUE TITLE
[Enhancement]: some suggestions in doc "CREATE TABLE" and "CREATE EXTERNAL TABLE"

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixorigin.io#244]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

1. the explanations is the parameters description of the Syntax? then maybe we can use table form uniformly？just like "CREATE EXTERNAL TABLE" and one more tip: we can left justifying in the table if there are many words.

2. if there are many examples, may be we can use more differentiated code blocks? to make sure the code can be copied in the item.

3. what is mean of the " Current Usage syntax" in "CREATE EXTERNAL TABLE"?

4. import the data from s3 ， or import data from s3 ？

**Comment by lacrimosaprinz** [comment]
the explanations is the parameters description of the Syntax? then maybe we can use table form uniformly？just like "CREATE EXTERNAL TABLE" and one more tip: we can left justifying in the table if there are many words.
===============》
I compared MySQL Docs, Tidb  Docs, Snowflake Docs, and Starrocks  Docs. Generally, the length of the artical is relatively long. Tidb doc is in the form of a table but the content is relatively small. Let’s keep it unchanged for the time being?
