### ISSUE TITLE
[Enhancement]: question in doc"PRIMARY KEY"

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixorigin.io#245]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

is "PRIMARY KEY" is s ddl sql statement? also we have unique key, foreign key etc.

I saw it as "Constraints" in some other docs. a little confused.

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/247
