### ISSUE TITLE
[Doc Request]: need a list of reserved words

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#248]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

We need a reserved words for MatrixOne, such as https://dev.mysql.com/doc/refman/8.0/en/keywords.html.

Please see with @iamlinjunhong with this. @la

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/261
