### ISSUE TITLE
[Enhancement]: create table

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#253]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.io/0.6.0/MatrixOne/Reference/SQL-Reference/Data-Definition-Statements/create-table/#examples

1. MatrixOne partition by is a fake one, only syntax is supported. No need to have so much content about it.
2. The examples 1-5 can have better category names.
3. Several partition by examples are wrong.

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/255
