### ISSUE TITLE
[Enhancement]: Add gcc as dependency

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#259]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.io/0.6.0/MatrixOne/Get-Started/install-standalone-matrixone/

Building MatrixOne from source requires gcc as dependency.

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/267
