### ISSUE TITLE
[Enhancement]: the user operations are not precisely filtered

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#263]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.io/0.6.0/MatrixOne/Troubleshooting/audit/#enable-audit

<img width="743" alt="image" src="https://user-images.githubusercontent.com/4965857/215685123-26c1f097-d69a-4210-b6b3-137100cd51ef.png">

This query will also print out system operation queries.
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/4965857/215685250-e467655c-eded-4eee-b792-951e78aec345.png">

**Comment by domingozhang** [comment]
create view mo_user_action as select request_at,user,host,statement,status from system.statement_info where user in (select distinct user_name from mo_catalog.mo_user) and statement not like '\_\___\_\_internal\_%' order by request_at desc;

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/280
