### ISSUE TITLE
[Enhancement]: error code

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#264]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.io/0.6.0/MatrixOne/Troubleshooting/error-code/

The current error code is a reference-like document. We need at least add some descriptions about what are they, where and how they are used.

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/279
