### ISSUE TITLE
[Enhancement]: Review Explain reference 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#270]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.io/0.6.0/MatrixOne/Reference/SQL-Reference/Utility-Statements/Explain/explain/

Looks like this hasn't been updated for quite some time. Please make a review. 

<img width="995" alt="image" src="https://user-images.githubusercontent.com/4965857/216224040-87aac13a-bcc4-46ad-a4ba-16e0ffb38f80.png">

https://docs.matrixorigin.io/0.6.0/MatrixOne/Reference/SQL-Reference/Utility-Statements/Explain/explain-workflow/#output-structure

<img width="546" alt="image" src="https://user-images.githubusercontent.com/4965857/216248975-821554b4-bd23-4033-879c-cc3627a36f2d.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/274
