### ISSUE TITLE
[Enhancement]: Deployment FAQ outdated

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io#271]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.io/0.6.0/MatrixOne/FAQs/deployment-faqs/#hardware-requirements

<img width="719" alt="image" src="https://user-images.githubusercontent.com/4965857/216249874-f4298939-4728-410d-b6ba-d84b257fd900.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/272
