### ISSUE TITLE
[Doc Request]: add guide for change data file location

### ISSUE THREAD

**Issue by cherryli127** [matrixorigin/matrixorigin.io#293]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

Please add a guide for changing data file location for 0.7 in both English & Chinese doc for developer support.

**Comment by lacrimosaprinz** [comment]
@domingozhang 

If I want to redirect the data store location, can I change the log.toml file parameters in the mo folder? 

log.toml
|data-dir = "./mo-data"|Default data directory|

**Comment by domingozhang** [comment]
This action can modify the data file path for file system.
