### ISSUE TITLE
[Enhancement]: Add illustration for date function reference 

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixorigin.io#495]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

Seems we are missing some important functions, like hour/minute/second, etc on our doc wesite. Please kindly help take a look if there's any plan to update them.
<img width="1288" alt="image" src="https://github.com/matrixorigin/matrixorigin.io/assets/46433151/07033fb4-73f6-4cda-bcc5-15a687324837">

**Comment by lacrimosaprinz** [comment]
doc：https://github.com/matrixorigin/matrixorigin.io/pull/502
https://github.com/matrixorigin/matrixorigin.io.cn/pull/659
